spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_nuevo2
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
