spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
