spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_nuevo2
    username: postgres
    password: password
    driverClassName: org.postgresql.Driver
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
